# Test53 LambdaCDM validation reference
h = 0.689782657631
T_cmb = 2.7255
omega_b = 0.0223828000
omega_cdm = 0.118327317147
N_ur = 2.03066666667
N_ncdm = 1
omega_ncdm = 0.0006451439
Omega_k = 0.
Omega_fld = 0.
Omega_scf = 0.
Omega_idm_dr = 0.
YHe = 0.2454006
tau_reio = 0.05430842
k_pivot = 0.05
A_s = 2.100549000e-09
n_s = 0.9660499
output = tCl,pCl,lCl,mPk
modes = s
lensing = yes
gauge = synchronous
P_k_ini type = analytic_Pk
l_max_scalars = 3000
non linear = halofit
write background = yes
write thermodynamics = yes
write primordial = yes
write parameters = yes
write warnings = yes
root = output/test53_lcdm_reference_
